style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/vaclav-dvorak/veribi-cli
options:
  commits:
    filters:
      Type:
        - feat
        - add
        - change
        - fix
        - refactor
  commit_groups:
    sort_by: Custom
    title_order:
      - feat
      - add
      - change
      - fix
      - refactor
    title_maps:
      feat: ğŸ‰ Features
      add: ğŸ“¦ Added
      change: ğŸ’¥ Changed
      fix: ğŸ Bug Fixes
      refactor: â™» Code Refactoring
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
